"""empty message

Revision ID: 98811e8464fc
Revises: 5607dd856831
Create Date: 2025-09-13 13:51:46.283932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98811e8464fc'
down_revision = '5607dd856831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('FARMER', 'COMPANY', 'FARM_IND', name='role'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
